//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristGuider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrderDetail
    {
        public long FdOdrDtID { get; set; }
        public Nullable<long> FdID { get; set; }
        public string Qty { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
