//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristGuider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentBooking
    {
        public long RtBkID { get; set; }
        public Nullable<long> CarID { get; set; }
        public Nullable<System.DateTime> DateBooked { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
        public string NoofDays { get; set; }
        public string TtlRt { get; set; }
        public Nullable<bool> isReturned { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
