//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristGuider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public long RmID { get; set; }
        public Nullable<long> HtlID { get; set; }
        public string RmNm { get; set; }
        public string RmRt { get; set; }
        public string RmImg { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
