//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristGuider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooking
    {
        public long RmBkID { get; set; }
        public Nullable<long> HtlID { get; set; }
        public Nullable<long> RmID { get; set; }
        public Nullable<long> TtlRt { get; set; }
        public Nullable<System.DateTime> ChkInDt { get; set; }
        public Nullable<System.DateTime> ChlOtDt { get; set; }
        public Nullable<bool> isCheckout { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
    }
}
